# Generated by Django 5.1.7 on 2025-04-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worker_images/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='ragting',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Worker_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='app1.worker')),
            ],
        ),
    ]
