# Generated by Django 5.1.7 on 2025-04-10 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker_count', models.PositiveIntegerField(default=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='app1.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='app1.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='app1.worker')),
            ],
        ),
    ]
