# Generated by Django 5.1.7 on 2025-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_hire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
