# Generated by Django 5.1.7 on 2025-04-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_order_expected_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
    ]
