# Generated by Django 5.1.7 on 2025-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
