# Generated by Django 5.1.7 on 2025-04-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_order_status_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_date',
        ),
    ]
