# Generated by Django 5.1.7 on 2025-04-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_order_expected_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karts', to='app1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karts', to='app1.user')),
            ],
        ),
    ]
