# Generated by Django 5.1.7 on 2025-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_kart'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
